name: chirpsdk
version: 0.4.0
description: Chirp enables your apps to send and receive information using sound.
author: Asio Ltd <developers@chirp.io>
homepage: https://github.com/chirp/chirp-flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.chirp.chirpsdk
    pluginClass: ChirpsdkPlugin
